import { auth, db, storage } from "./firebase-config.js";
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { doc, getDoc, setDoc, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import { getDownloadURL, ref, uploadBytes } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-storage.js";

const app = document.querySelector("#app");
const state = { page: "login", role: "member", approved: false, user: null, firebaseUser: null };

const logo = "assets/panther-badge.png";
const wordmark = "assets/panther-wordmark.png";
function setPage(page){state.page=page; render()}
function saveUser(user){state.user=user; localStorage.setItem("pm_user",JSON.stringify(user))}
function showError(error){const target=document.querySelector("#form-error");if(target) target.textContent=error?.code==="auth/email-already-in-use"?"Email sudah terdaftar.":error?.code==="auth/invalid-credential"?"Email atau password salah.":error?.message||"Terjadi kesalahan. Silakan coba lagi."}
async function uploadDocument(userId, file, folder){if(!file?.size)return "";if(file.size>5*1024*1024)throw new Error("Ukuran file maksimal 5MB.");const fileRef=ref(storage,`members/${userId}/${folder}-${Date.now()}-${file.name}`);await uploadBytes(fileRef,file,{contentType:file.type});return getDownloadURL(fileRef)}
function field(label, name, type="text", extra=""){return `<div class="field ${extra}"><label>${label}</label><input name="${name}" type="${type}" required /></div>`}
function authPage(register=false){
  return `<main class="auth"><section class="auth-box">
    <img class="auth-logo" src="${wordmark}" alt="Panther Mania">
    <h1>${register?"Daftar Member":"Selamat datang kembali"}</h1><p class="auth-sub">${register?"Bergabung dengan keluarga Panther Mania Indonesia.":"Masuk ke ruang komunitas Anda."}</p>
    <form id="auth-form">${register?`<div class="form-grid">${field("Nama lengkap","name","text","full")}${field("Email aktif","email","email")}${field("Nomor HP aktif","phone","tel")}${field("Nomor KTP","ktp","text")}${field("Nomor SIM","sim","text")}${field("Password","password","password")}<div class="field"><label>Foto KTP</label><input name="ktpPhoto" type="file" accept="image/*" required /></div><div class="field"><label>Foto SIM</label><input name="simPhoto" type="file" accept="image/*" required /></div><div class="field full"><label>Bukti pembayaran</label><input name="paymentPhoto" type="file" accept="image/*" required /></div></div><div class="notice">📷 Dokumen disimpan privat di Firebase Storage dan hanya digunakan untuk verifikasi.</div>`:`${field("Email","email","email")}${field("Password","password","password")}<div class="notice">Akses admin menggunakan akun Firebase dengan custom claim <b>admin: true</b>.</div>`}<p id="form-error" class="error-text"></p><button class="btn" type="submit">${register?"Buat akun member":"Masuk ke dashboard"}</button></form>
    <p class="switch">${register?"Sudah punya akun?":"Belum punya akun?"} <span class="link" data-page="${register?"login":"register"}>${register?"Masuk":"Daftar sekarang"}</span></p>
  </section></main>`;
}
function sidebar(){
  return `<aside class="sidebar"><div class="brand"><img src="${logo}" alt=""><div>PANTHER<small>MANIA INDONESIA</small></div></div>
    <nav class="nav">${state.role==="admin"?`<button data-page="admin" class="${state.page==="admin"?"active":""}">▦ &nbsp; Member approval</button>`:`<button data-page="dashboard" class="${state.page==="dashboard"?"active":""}">⌂ &nbsp; Overview</button><button data-page="profile" class="${state.page==="profile"?"active":""}">♙ &nbsp; Profil saya</button><button data-page="card" class="${state.page==="card"?"active":""}">▣ &nbsp; ID member</button>`}</nav>
    <div class="sidebar-bottom">Panther Mania v1.0<br><span>Made for the family.</span></div></aside>`;
}
function layout(content,title="Dashboard"){
  return `<div class="shell">${sidebar()}<main class="main"><header class="topbar"><div class="brand"><img src="${logo}" alt=""><div>PANTHER<small>MANIA INDONESIA</small></div></div><div class="user-chip"><span class="mobile-hide">${state.role==="admin"?"Administrator":"Halo, "+(state.user?.name||"Member")}</span><span class="avatar">${state.role==="admin"?"A":"M"}</span><button class="btn ghost tiny" id="logout">Keluar</button></div></header>${content}</main></div>`;
}
function dashboard(){
 return layout(`<div class="hero"><div><span class="eyebrow">Member portal</span><h1>Selamat datang,<br>${state.user?.name?.split(" ")[0]||"Member"}.</h1><p>Semua yang Anda butuhkan untuk tetap terhubung dengan keluarga Panther Mania.</p></div><img class="hero-art" src="assets/panther-car.webp" alt="Mitsubishi Panther"><button class="btn" data-page="profile">Lengkapi profil →</button></div>
 <div class="grid"><div class="card stat"><span class="label">Status keanggotaan</span><strong>Aktif</strong><small>● Terverifikasi</small></div><div class="card stat"><span class="label">Nomor member</span><strong>PM-2026</strong><small>Sejak 20 Sep 2026</small></div><div class="card stat"><span class="label">Kegiatan diikuti</span><strong>08</strong><small>+2 bulan ini</small></div><div class="card stat"><span class="label">Poin komunitas</span><strong>1.240</strong><small>Top 12% member</small></div>
 <section class="card wide"><div class="card-head"><h2>Aktivitas terbaru</h2><span class="badge">Live</span></div><div class="activity">${["Registrasi member berhasil","Profil dasar telah diverifikasi","Selamat datang di Panther Mania"].map((x,i)=>`<div class="activity-row"><span class="activity-icon">${["✓","♙","✦"][i]}</span><div><strong>${x}</strong><small>${i?"20 Sep 2026":"Baru saja"}</small></div></div>`).join("")}</div></section>
 <section class="card side member-card"><div class="card-head"><h2>Digital ID</h2><span class="badge">Verified</span></div><img class="mini-logo" src="${wordmark}" alt=""><div class="member-id"><div><small class="muted">MEMBER ID</small><strong>PM-260920</strong></div><span style="font-size:35px">▦</span></div><button class="btn ghost tiny" style="margin-top:20px" data-page="card">Lihat kartu digital</button></section></div>`);
}
function profile(){
 return layout(`<div class="hero"><div><span class="eyebrow">Data pribadi</span><h1>Lengkapi profil.</h1><p>Profil yang lengkap membantu kami menjaga komunitas tetap aman dan terhubung.</p></div></div><div class="profile-layout"><section class="card"><div class="profile-photo"><span class="photo-placeholder">♙</span></div><button class="btn secondary" style="width:100%;margin-top:13px">＋ Upload foto</button><p class="muted" style="font-size:12px;text-align:center">JPG/PNG maksimal 2MB</p></section><section class="card"><form id="profile-form"><div class="form-grid">${field("Agama","religion")}<div class="field"><label>Jenis kelamin</label><select><option>Pilih jenis kelamin</option><option>Laki-laki</option><option>Perempuan</option></select></div><div class="field"><label>Status menikah</label><select><option>Belum menikah</option><option>Menikah</option></select></div>${field("Pekerjaan","job")}${field("Nama perusahaan (opsional)","company")}${field("Alamat","address","text","full")}${field("Link Google Maps (opsional)","maps","url","full")}</div><div class="card-head" style="margin-top:12px"><h2>Titik lokasi rumah</h2><span class="muted" style="font-size:12px">Geser pin untuk menyesuaikan</span></div><div class="map" id="map"><span class="pin" id="pin"></span><span class="map-tip">📍 Jakarta Selatan · -6.2615, 106.8106</span></div><button class="btn" type="submit" style="margin-top:18px">Simpan perubahan</button></form></section></div>`);
}
function cardPage(){return layout(`<div class="hero"><div><span class="eyebrow">Identitas digital</span><h1>Kartu member.</h1><p>Tunjukkan ID ini saat hadir di kegiatan resmi Panther Mania.</p></div></div><section class="card member-card" style="max-width:650px;padding:30px"><div class="card-head"><img class="mini-logo" src="${wordmark}" alt=""><span class="badge">MEMBER AKTIF</span></div><p class="muted" style="margin-top:45px;margin-bottom:4px">NAMA MEMBER</p><h2 style="font-size:28px">${state.user?.name||"Member Panther Mania"}</h2><div class="member-id"><div><small class="muted">ID ANGGOTA</small><strong>PM-260920</strong></div><div style="background:#fff;color:#111;padding:8px;border-radius:8px;font-size:27px;letter-spacing:2px">▦ ▦<br>▦ ▦</div></div></section>`)}
function admin(){return layout(`<div class="hero"><div><span class="eyebrow">Administrator</span><h1>Approval member.</h1><p>Review pendaftaran baru dan jaga kualitas keluarga Panther Mania.</p></div><span class="badge pending">1 menunggu review</span></div><section class="card"><div class="card-head"><h2>Registrasi terbaru</h2><span class="muted">20 September 2026</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Member</th><th>Kontak</th><th>Dokumen</th><th>Status</th><th>Aksi</th></tr></thead><tbody><tr><td><b>${state.user?.name||"Budi Santoso"}</b><br><small class="muted">Daftar hari ini</small></td><td>${state.user?.email||"member@email.com"}<br>${state.user?.phone||"08xx"}</td><td><span class="badge">KTP ✓</span> <span class="badge">SIM ✓</span></td><td><span class="badge pending">${state.approved?"Disetujui":"Menunggu"}</span></td><td class="table-actions">${state.approved?`<button class="btn tiny secondary" disabled>ID PM-260920</button>`:`<button class="btn tiny" id="approve">Approve & generate ID</button>`}</td></tr></tbody></table></div></section>`) }
function render(){
 if(state.page==="login") app.innerHTML=authPage(); else if(state.page==="register") app.innerHTML=authPage(true); else if(state.page==="waiting") app.innerHTML=layout(`<div class="empty card"><div class="emoji">⏳</div><h3>Pendaftaran sedang direview</h3><p>Dokumen Anda sudah kami terima. Admin akan memverifikasi data dalam 1×24 jam.</p><button class="btn ghost" style="margin-top:22px" id="logout">Kembali</button></div>`); else if(state.page==="admin") app.innerHTML=admin(); else if(state.page==="profile") app.innerHTML=profile(); else if(state.page==="card") app.innerHTML=cardPage(); else app.innerHTML=dashboard();
 document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>setPage(x.dataset.page));
 document.querySelector("#logout")?.addEventListener("click",async()=>{await signOut(auth);state.page="login";render()});
 document.querySelector("#auth-form")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.target;const d=Object.fromEntries(new FormData(form));const submit=form.querySelector("button[type=submit]");submit.disabled=true;try{if(state.page==="register"){const credential=await createUserWithEmailAndPassword(auth,d.email,d.password);const [ktpPhoto,simPhoto,paymentPhoto]=await Promise.all([uploadDocument(credential.user.uid,d.ktpPhoto,"ktp"),uploadDocument(credential.user.uid,d.simPhoto,"sim"),uploadDocument(credential.user.uid,d.paymentPhoto,"payment")]);await setDoc(doc(db,"members",credential.user.uid),{uid:credential.user.uid,name:d.name,email:d.email,phone:d.phone,ktp:d.ktp,sim:d.sim,status:"pending",ktpPhoto,simPhoto,paymentPhoto,createdAt:serverTimestamp()});state.user={name:d.name,email:d.email,phone:d.phone};state.page="waiting"}else{const credential=await signInWithEmailAndPassword(auth,d.email,d.password);const token=await credential.user.getIdTokenResult(true);state.role=token.claims.admin===true?"admin":"member";const member=await getDoc(doc(db,"members",credential.user.uid));if(member.exists()){const data=member.data();state.user=data;state.approved=data.status==="approved";state.page=state.role==="admin"?"admin":state.approved?"dashboard":"waiting"}else{state.page=state.role==="admin"?"admin":"waiting"}}render()}catch(error){showError(error);submit.disabled=false}});
 document.querySelector("#approve")?.addEventListener("click",async()=>{if(!state.firebaseUser)return;await updateDoc(doc(db,"members",state.firebaseUser.uid),{status:"approved",approvedAt:serverTimestamp(),memberId:"PM-"+String(Date.now()).slice(-6)});state.approved=true;render()});
 document.querySelector("#profile-form")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.target;const data=Object.fromEntries(new FormData(form));await updateDoc(doc(db,"members",state.firebaseUser.uid),{...data,updatedAt:serverTimestamp()});state.user={...state.user,...data};saveUser(state.user);alert("Profil berhasil disimpan.");setPage("dashboard")});
 const map=document.querySelector("#map");if(map){map.addEventListener("click",e=>{const r=map.getBoundingClientRect();const p=document.querySelector("#pin");p.style.left=`${e.clientX-r.left}px`;p.style.top=`${e.clientY-r.top}px`})}
}
render();
