org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Users\\AbidSukses\\.jdks\\jbr-21.0.11
systemProp.android.user.home=C:\\Users\\AbidSukses\\.android
systemProp.ANDROID_USER_HOME=C:\\Users\\AbidSukses\\.android
